Fix podman detection
Addresses two issues with podman/docker selection:
* /bin/sh (dash) on Ubuntu LTS 20.04 doesn't know the `&>` shortcut for
  `2>&1 >/dev/null`
* podman fails with the following error in GitHub actions on
  `ubuntu-latest` (Ubuntu LTS 20.04):

  ```
  Error: Error committing the finished image: error adding layer with
  blob "sha256:<sum>": Error processing tar file(exit status 1):
  operation not permitted
  ```